import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import sql from './db.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Auto-generated Migration Runner
 * 
 * This file is AUTO-GENERATED by 'yarn generate-entities'
 * DO NOT EDIT MANUALLY - changes will be overwritten!
 * 
 * Migrations are automatically discovered from src/lib/migrations/*.sql
 * To add a migration, create a new .sql file and run 'yarn generate-entities'
 */

async function migrate() {
	try {
		console.log('Running migrations...\n');

		// 001.notes.sql
		const migration_001_notes_sql = await readFile(
			join(__dirname, 'migrations', '001.notes.sql'),
			'utf-8'
		);
		await sql.unsafe(migration_001_notes_sql);
		console.log('✓ Migration 001.notes.sql completed');

		// 001.products.sql
		const migration_001_products_sql = await readFile(
			join(__dirname, 'migrations', '001.products.sql'),
			'utf-8'
		);
		await sql.unsafe(migration_001_products_sql);
		console.log('✓ Migration 001.products.sql completed');

		await sql.end();
		console.log('\n✓ All migrations completed');
	} catch (error) {
		console.error('Migration failed:', error);
		await sql.end();
		process.exit(1);
	}
}

migrate();
