/**
 * Auto-generated CRUD Operations from Entity Config
 * 
 * This file is AUTO-GENERATED by 'yarn generate-entities'
 * DO NOT EDIT MANUALLY - changes will be overwritten!
 * 
 * To add/modify entities, edit src/lib/db/entities.config.ts
 * then run 'yarn generate-entities'
 */

import { createCrud } from './crud-factory';
import { entities } from './entities.config';

// Generate CRUD operations for notes
const notesCrud = createCrud(entities.notes);

export const getAllNotes = notesCrud.getAll;
export const getNotes = notesCrud.getById;
export const createNotes = notesCrud.create;
export const updateNotes = notesCrud.update;
export const deleteNotes = notesCrud.delete;

