/**
 * Database Entity Registry
 * 
 * This file is AUTO-GENERATED by 'yarn generate-entities'
 * DO NOT EDIT MANUALLY - changes will be overwritten!
 * 
 * Usage:
 *   import { db } from '$lib/db/registry';
 *   const items = await db.entityName.getAll();
 *   await db.entityName.create({ ... });
 */

import {
	getAllNotes,
	getNotes,
	createNotes,
	updateNotes,
	deleteNotes,
} from './entities.remote';

export const db = {
	notes: {
		getAll: getAllNotes,
		getById: getNotes,
		create: createNotes,
		update: updateNotes,
		delete: deleteNotes
	},
};

// Type-safe access to all entities
export type DbEntity = keyof typeof db;
