-- Auto-generated migration for notes
-- Generated by 'yarn generate-entities'

CREATE TABLE IF NOT EXISTS notes (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);
